/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Form.ShowDataSiswa;
import Form.ShowDataPetugas;
import static Frame.EntriTransaksi.frmInstance;
import Konfigurasi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A AAKHIF ATHALLAH
 */
public class EntriTransaksi extends javax.swing.JInternalFrame {

    /**
     * Creates new form EntriTransaksi1
     */
    //    MAKE TXTFIELD PUBLIC
    public static EntriTransaksi frmInstance;
    public JTextField txtPetugasPub, txtIdSppPub, txtNisnPub, txtNominalPub;
    
    private DefaultTableModel DftTblModel_EntriTransaksi;
    private String SQL;
    
    public void TampilData() {
        DftTblModel_EntriTransaksi = new DefaultTableModel();
        DftTblModel_EntriTransaksi.addColumn("ID PEMBAYARAN");
//        DftTblModel_EntriTransaksi.addColumn("ID PETUGAS");
        DftTblModel_EntriTransaksi.addColumn("NAMA");
        DftTblModel_EntriTransaksi.addColumn("TGL BAYAR");
        DftTblModel_EntriTransaksi.addColumn("BULAN DIBAYAR");
        DftTblModel_EntriTransaksi.addColumn("TAHUN DIBAYAR");
//        DftTblModel_EntriTransaksi.addColumn("ID SPP");
        DftTblModel_EntriTransaksi.addColumn("JUMLAH BAYAR");
        tblEntriTransaksi.setModel(DftTblModel_EntriTransaksi);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select id_pembayaran, nama, tgl_bayar, bulan_dibayar, tahun_dibayar, jumlah_bayar from pembayaran inner join siswa on pembayaran.nisn = siswa.nisn";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_EntriTransaksi.addRow(new Object[]{
                    res.getString("id_pembayaran"),
//                    res.getString("id_petugas"),
                    res.getString("nama"),
                    res.getString("tgl_bayar"),
                    res.getString("bulan_dibayar"),
                    res.getString("tahun_dibayar"),
//                    res.getString("id_spp"),
                    res.getString("jumlah_bayar")});
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void randNum() {
        try {
            Integer randomNum = ThreadLocalRandom.current().nextInt(10000000, 99999998 + 1);
            String key = randomNum.toString();;

            int num = 0;

            System.out.println(key);

            Connection conn = Koneksi.getConnection();
            String sql = "SELECT Count(*) as jml FROM pembayaran WHERE id_pembayaran = '" + key + "'";
            Statement stmt = conn.createStatement();
            ResultSet res = stmt.executeQuery(sql);
            if (res.next()) {
                num = Integer.parseInt(res.getObject("jml").toString());
                if (num > 0) {
                    key = randomNum.toString();
                } else {
                    txtIdPembayaran.setText(key);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Login Gagal", "", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }
    
    public EntriTransaksi() {
        initComponents();
        TampilData();
//        MAKE TXTFIELD PUBLIC
        frmInstance = this;
        txtPetugasPub = txtIdPetugas;
        txtIdSppPub = txtIdSpp;
        txtNisnPub = txtName;
        txtNominalPub = txtJumlahBayar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdPembayaran = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIdPetugas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntriTransaksi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdSpp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtJumlahBayar = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnHelpSpp = new javax.swing.JButton();
        btnHelpSpp1 = new javax.swing.JButton();
        cbBulanDibayar = new javax.swing.JComboBox<>();
        cbTahunDibayar = new javax.swing.JComboBox<>();
        btnRefreshData = new javax.swing.JButton();
        txtTglBayar = new com.toedter.calendar.JDateChooser();

        setMinimumSize(new java.awt.Dimension(1080, 565));
        setPreferredSize(new java.awt.Dimension(1080, 565));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("ENTRI TRANSAKSI PEMBAYARAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        txtIdPembayaran.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtIdPembayaran.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("ID PEMBAYARAN");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Generate new ID Pembayaran");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("ID PETUGAS");

        txtIdPetugas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtIdPetugas.setEnabled(false);

        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tblEntriTransaksi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblEntriTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEntriTransaksi.setRowHeight(30);
        tblEntriTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEntriTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblEntriTransaksiMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblEntriTransaksi);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("NAME");

        txtName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtName.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("TANGGAL BAYAR");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("BULAN DIBAYAR");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("TAHUN DIBAYAR");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("ID SPP");

        txtIdSpp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtIdSpp.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("JUMLAH BAYAR");

        txtJumlahBayar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtJumlahBayar.setEnabled(false);
        txtJumlahBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahBayarActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClear.setText("CLEAR FIELD");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnHelpSpp.setText("?");
        btnHelpSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpSppActionPerformed(evt);
            }
        });

        btnHelpSpp1.setText("?");
        btnHelpSpp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpSpp1ActionPerformed(evt);
            }
        });

        cbBulanDibayar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbBulanDibayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        cbTahunDibayar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbTahunDibayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));

        btnRefreshData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRefreshData.setText("REFRESH DATA");
        btnRefreshData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshDataActionPerformed(evt);
            }
        });

        txtTglBayar.setDateFormatString("yyyy-MM-dd");
        txtTglBayar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIdPembayaran)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIdPetugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHelpSpp1)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(cbBulanDibayar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jButton1)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTglBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtIdSpp, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbTahunDibayar, javax.swing.GroupLayout.Alignment.LEADING, 0, 183, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnHelpSpp)))))
                    .addComponent(txtJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefreshData, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefreshData))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHelpSpp1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdSpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHelpSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addComponent(txtTglBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBulanDibayar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTahunDibayar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear)
                            .addComponent(btnSave)
                            .addComponent(btnEdit)
                            .addComponent(btnDelete))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        randNum();
        btnClear.setEnabled(true);
        btnSave.setEnabled(true);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtJumlahBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBayarActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtIdPembayaran.setText(null);
        txtIdPetugas.setText(null);
        txtName.setText(null);
        txtTglBayar.setDate(null);
        cbBulanDibayar.setSelectedItem("Januari");
        cbTahunDibayar.setSelectedItem("2000");
        txtIdSpp.setText(null);
        txtJumlahBayar.setText(null);
        btnSave.setEnabled(true);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHelpSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpSppActionPerformed
        ShowDataSiswa dataSiswa = new ShowDataSiswa();
        dataSiswa.dispose();
        dataSiswa.setVisible(true);
    }//GEN-LAST:event_btnHelpSppActionPerformed

    private void btnHelpSpp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpSpp1ActionPerformed
        ShowDataPetugas dataPetugas = new ShowDataPetugas();
        dataPetugas.dispose();
        dataPetugas.setVisible(true);
    }//GEN-LAST:event_btnHelpSpp1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Connection conn = Koneksi.getConnection();
            if (txtIdPembayaran.getText().isEmpty() || txtIdPetugas.getText().isEmpty() || txtIdSpp.getText().isEmpty() || txtName.getText().isEmpty() || txtTglBayar.getDate() == null || cbBulanDibayar.getSelectedItem().toString().isEmpty() || cbTahunDibayar.getSelectedItem().toString().isEmpty() || txtJumlahBayar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Make sure the data is filled in correctly!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                int num = 0;
                String sql = "SELECT Count(*) as jml FROM pembayaran INNER JOIN siswa ON pembayaran.nisn = siswa.nisn WHERE pembayaran.id_spp = '" + txtIdSpp.getText() + "' AND bulan_dibayar = '"+ cbBulanDibayar.getSelectedItem() +"'";
                Statement stmtn = conn.createStatement();
                ResultSet res = stmtn.executeQuery(sql);
                if (res.next()) {
                    num = Integer.parseInt(res.getObject("jml").toString());
                    if (num > 0) {
//                        CONDITION IF GAGAL
                        String sqlComm2 = "SELECT DISTINCT siswa.nama FROM pembayaran INNER JOIN siswa ON pembayaran.nisn = siswa.nisn WHERE pembayaran.id_spp = '"+txtIdSpp.getText()+"'";
                        Statement stmtn2   = conn.createStatement();
                        ResultSet res2 = stmtn2.executeQuery(sqlComm2);
                        if (res2.next()) {
                            String Nama = res2.getObject("nama").toString();
                            JOptionPane.showMessageDialog(null, "SPP payment on behalf of "+ Nama +" in "+ cbBulanDibayar.getSelectedItem() +" has been paid", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
//                        CONDITION IF TRUE
                        
                        
                        
                        PreparedStatement stmt = conn.prepareStatement("insert  into  pembayaran(id_pembayaran,  id_petugas, id_spp, nisn, tgl_bayar, bulan_dibayar, tahun_dibayar, jumlah_bayar) values(?,?,?,?,?,?,?,?)");
                        stmt.setString(1, txtIdPembayaran.getText());
                        stmt.setString(2, txtIdPetugas.getText());
                        stmt.setString(3, txtIdSpp.getText());
                        
//                        SAVE NISN TO PEMBAYARAN
                        String sql2 = "SELECT DISTINCT nisn FROM siswa WHERE nama = '"+txtName.getText()+"'";
                        Statement stmtn2   = conn.createStatement();
                        ResultSet res2 = stmtn2.executeQuery(sql2);
                        if (res2.next()) {
                            String Nama = res2.getObject("nisn").toString();
                            stmt.setString(4, Nama);
                        }
//                        
                        
//                        DATE TO STRING SAVE
                        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
                        String strDate = formatter.format(txtTglBayar.getDate());  
                        stmt.setString(5, strDate);
//                        

                        stmt.setString(6, cbBulanDibayar.getSelectedItem().toString());
                        System.out.println(strDate);
                        stmt.setString(7, cbTahunDibayar.getSelectedItem().toString());
                        stmt.setString(8, txtJumlahBayar.getText());
                        stmt.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Data saved successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
                        TampilData();
                        txtIdPembayaran.setText("");
                        txtIdPetugas.setText("");
                        txtIdSpp.setText("");
                        txtName.setText("");
                        txtTglBayar.setDate(null); 
                        cbBulanDibayar.setSelectedItem("Januari");
                        cbTahunDibayar.setSelectedItem("2000");
                        txtJumlahBayar.setText("");
                        btnSave.setEnabled(false);
                    }
                    
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Make sure the data is filled in correctly!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            Connection conn = Koneksi.getConnection();
            if (txtIdPembayaran.getText().isEmpty() || txtIdPetugas.getText().isEmpty() || txtIdSpp.getText().isEmpty() || txtName.getText().isEmpty() || txtTglBayar.getDate() == null|| cbBulanDibayar.getSelectedItem().toString().isEmpty() || cbTahunDibayar.getSelectedItem().toString().isEmpty() || txtJumlahBayar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Make sure the data is filled in correctly!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
                String strDate = dateFormat.format(txtTglBayar.getDate());
                
                PreparedStatement stmt = conn.prepareStatement("update pembayaran set id_petugas=?, id_spp=?, nisn=?, tgl_bayar=?, bulan_dibayar=?, tahun_dibayar=?, jumlah_bayar=? where id_pembayaran=?");
                stmt.setString(1, txtIdPetugas.getText());
                stmt.setString(2, txtIdSpp.getText());
                
//                        EDIT NISN TO PEMBAYARAN
                        String sql2 = "SELECT DISTINCT nisn FROM siswa WHERE nama = '"+txtName.getText()+"'";
                        Statement stmtn2   = conn.createStatement();
                        ResultSet res2 = stmtn2.executeQuery(sql2);
                        if (res2.next()) {
                            String Nama = res2.getObject("nisn").toString();
                            stmt.setString(3, Nama);
                        }
//                        

                stmt.setString(4, strDate.toString());
                stmt.setString(5, cbBulanDibayar.getSelectedItem().toString());
                stmt.setString(6, cbTahunDibayar.getSelectedItem().toString());
                stmt.setString(7, txtJumlahBayar.getText());
                stmt.setString(8, txtIdPembayaran.getText());
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Changed Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
                TampilData();
                txtIdPembayaran.setText("");
                txtIdPetugas.setText("");
                txtIdSpp.setText("");
                txtName.setText("");
                txtTglBayar.setDate(null);  
                cbBulanDibayar.setSelectedItem("Januari");
                cbTahunDibayar.setSelectedItem("2000");
                txtJumlahBayar.setText("");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        btnSave.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblEntriTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEntriTransaksiMouseClicked
        
        Connection conn = Koneksi.getConnection();
        
        int baris = tblEntriTransaksi.getSelectedRow();
        txtIdPembayaran.setText(DftTblModel_EntriTransaksi.getValueAt(baris, 0).toString());
        
//        MENCARI ID PETUGAS
        try {
            String sql = "SELECT id_petugas FROM pembayaran WHERE id_pembayaran = '" + txtIdPembayaran.getText() + "'";
            Statement stmt = conn.createStatement();
            ResultSet res = stmt.executeQuery(sql);
            if (res.next()) {
                txtIdPetugas.setText(res.getObject("id_petugas").toString());
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Memilih :D\nKocak se lek awkmu ndelok error iki\n Periksa database mu, pasti onk sng salah input", "", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
//        
        
        String sdate = DftTblModel_EntriTransaksi.getValueAt(baris, 2).toString();
        try {  
            Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(sdate);
            txtName.setText(DftTblModel_EntriTransaksi.getValueAt(baris, 1).toString());
            txtTglBayar.setDate(date1);
            cbBulanDibayar.setSelectedItem(DftTblModel_EntriTransaksi.getValueAt(baris, 3).toString());
            cbTahunDibayar.setSelectedItem(DftTblModel_EntriTransaksi.getValueAt(baris, 4).toString());
        } catch (ParseException ex) {
            Logger.getLogger(EntriTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
//        MENCARI ID SPP
        try {
            String sql = "SELECT id_spp FROM pembayaran WHERE id_pembayaran = '" + txtIdPembayaran.getText() + "'";
            Statement stmt = conn.createStatement();
            ResultSet res = stmt.executeQuery(sql);
            if (res.next()) {
                txtIdSpp.setText(res.getObject("id_spp").toString());
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Memilih :D\nKocak se lek awkmu ndelok error iki\n Periksa database mu, pasti onk sng salah input", "", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
//        

        txtJumlahBayar.setText(DftTblModel_EntriTransaksi.getValueAt(baris, 5).toString());
        btnClear.setEnabled(true);
        btnSave.setEnabled(false);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_tblEntriTransaksiMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Connection conn = Koneksi.getConnection();
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the data?", "Warning!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == 0) {
            try {
                java.sql.PreparedStatement stmt = conn.prepareStatement("delete from pembayaran where id_pembayaran ='" + txtIdPembayaran.getText() + "' and id_petugas ='"+txtIdPetugas.getText()+"' and id_spp ='"+txtIdSpp.getText()+"'");
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data deleted successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                TampilData();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data failed to delete" + e.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
            }
        }
        TampilData();
        txtIdPembayaran.setText("");
        txtIdPetugas.setText("");
        txtIdSpp.setText("");
        txtName.setText("");
        txtTglBayar.setDate(null); 
        cbBulanDibayar.setSelectedItem("Januari");
        cbTahunDibayar.setSelectedItem("2000");
        txtJumlahBayar.setText("");
        btnClear.setEnabled(true);
        btnSave.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshDataActionPerformed
        TampilData();
    }//GEN-LAST:event_btnRefreshDataActionPerformed

    private void tblEntriTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEntriTransaksiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEntriTransaksiMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHelpSpp;
    private javax.swing.JButton btnHelpSpp1;
    private javax.swing.JButton btnRefreshData;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbBulanDibayar;
    private javax.swing.JComboBox<String> cbTahunDibayar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEntriTransaksi;
    private javax.swing.JTextField txtIdPembayaran;
    private javax.swing.JTextField txtIdPetugas;
    private javax.swing.JTextField txtIdSpp;
    private javax.swing.JTextField txtJumlahBayar;
    private javax.swing.JTextField txtName;
    private com.toedter.calendar.JDateChooser txtTglBayar;
    // End of variables declaration//GEN-END:variables
}
