/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Account.LoginPageSiswa;
//import Konfigurasi.Autentikasi;
import Konfigurasi.Koneksi;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A AAKHIF ATHALLAH
 */
public class HistoryPembayaranSiswa extends javax.swing.JInternalFrame {

    /**
     * Creates new form HistoryPembayaranSiswa
     */
    
   
    
    private DefaultTableModel DftTblModel_HistoryPembayaran;
    private String SQL;
    public int idSpp;
   
    
    public void TampilData() {
//        Autentikasi auth = new Autentikasi();
        
        DftTblModel_HistoryPembayaran = new DefaultTableModel();
        DftTblModel_HistoryPembayaran.addColumn("ID PEMBAYARAN");
        DftTblModel_HistoryPembayaran.addColumn("ID PETUGAS");
        DftTblModel_HistoryPembayaran.addColumn("NISN");
        DftTblModel_HistoryPembayaran.addColumn("TGL BAYAR");
        DftTblModel_HistoryPembayaran.addColumn("BULAN DIBAYAR");
        DftTblModel_HistoryPembayaran.addColumn("TAHUN DIBAYAR");
        DftTblModel_HistoryPembayaran.addColumn("ID SPP");
        DftTblModel_HistoryPembayaran.addColumn("JUMLAH BAYAR");
        tblHistoryPembayaran.setModel(DftTblModel_HistoryPembayaran);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from pembayaran WHERE id_spp ='"+this.idSpp+"'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_HistoryPembayaran.addRow(new Object[]{
                    res.getString("id_pembayaran"),
                    res.getString("id_petugas"),
                    res.getString("nisn"),
                    res.getString("tgl_bayar"),
                    res.getString("bulan_dibayar"),
                    res.getString("tahun_dibayar"),
                    res.getString("id_spp"),
                    res.getString("jumlah_bayar")});
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public HistoryPembayaranSiswa(int idSpp) {
        initComponents();
        this.idSpp = idSpp;
        TampilData();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistoryPembayaran = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1080, 565));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("HISTORY PEMBAYARAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        tblHistoryPembayaran.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tblHistoryPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHistoryPembayaran.setEnabled(false);
        tblHistoryPembayaran.setRowHeight(50);
        jScrollPane1.setViewportView(tblHistoryPembayaran);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistoryPembayaran;
    // End of variables declaration//GEN-END:variables
}
